server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  rabbitmq:
      host: 192.168.25.7
      port: 5672
      username: guest
      password: guest
